# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['run_app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('interface.py', '.'),
        ('main.py', '.'),  # Adicionado main.py
        ('apostas.db', '.'),
        ('requirements.txt', '.'),
        ('usuarios.py', '.'),
        ('autenticacao.py', '.'),
        ('ml_previsoes.py', '.'),
        ('ml_rapido.py', '.'),
        ('banca.py', '.'),
        ('analise.py', '.'),
        ('analise_risco.py', '.'),
        ('comportamento_risco.py', '.'),
        ('dashboard_avancado.py', '.'),
        ('detecao_padroes.py', '.'),
        ('estatisticas.py', '.'),
        ('historico.py', '.'),
        ('importacao_dados.py', '.'),
        ('notificacoes_email.py', '.'),
        ('relatorios.py', '.'),
        ('seguranca.py', '.'),
        ('simulador_estrategias.py', '.'),
        ('temas.py', '.'),
        ('tipster_tracker.py', '.'),
        ('traducoes.py', '.'),
        ('validacao.py', '.'),
        ('visualizacoes_avancadas.py', '.'),
        ('alertas_inteligentes.py', '.'),
        ('config.json', '.'),
        ('config_email.json', '.'),
        ('config_idioma.json', '.'),
        ('config_seguranca.json', '.'),
        ('config_temas.json', '.'),
        ('configuracoes.json', '.'),
        ('icon.ico', '.'),
        ('temas', 'temas'),
        ('traducoes', 'traducoes'),
        ('modelos_ml', 'modelos_ml'),
        ('logs', 'logs'),
        ('config', 'config'),
        ('exports', 'exports'),
        ('backups', 'backups'),
        ('data', 'data'),
    ],
    hiddenimports=[
        'customtkinter',
        'pandas',
        'matplotlib',
        'cryptography',
        'reportlab',
        'PIL',
        'tkinter',
        'sqlite3',
        'json',
        'datetime',
        'threading',
        'pathlib',
        'typing',
        'logging',
        'traceback',
        'os',
        'sys',
        'time',
        'seaborn',  # Adicionado seaborn
        'dataclasses',
        'enum',
        'requests',
    ],
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='ApostasDesportivas',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='ApostasDesportivas',
    distpath='Compilacaot_corrigida',
)